# Generated by Django 4.0.3 on 2022-03-25 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customer_password'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customer',
            table='tbl_customers',
        ),
    ]
