# Generated by Django 4.0.3 on 2022-03-28 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='detail',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='order',
            name='title',
            field=models.CharField(default='title', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('customer',)},
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_id',
        ),
    ]
