# Generated by Django 4.0.3 on 2022-03-29 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_customer_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='detail',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
