# Generated by Django 4.0.3 on 2022-04-03 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_order_items_alter_order_detail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='detail',
            new_name='description',
        ),
    ]
